### ISSUE TITLE
Make header clickable

### ISSUE THREAD

**Issue by deBasMan21** [alexeichhorn/SwiftUINavigationHeader#1]
Hey there!

I love this package! It is working perfectly in my project. I just would like one extra feature. Is it okay if a open a pull request that makes it possible to add a callback that gets called when the header is tapped. This way i can add the possibility to open an image in fullscreen when someone clicks on it.

**Comment by alexeichhorn** [comment]
Look at my latest commit, I pushed just now. I think that's a better solution. It allows you to place a button inside the header view or wrap it inside a button. So you should be way more flexible than with a callback 😀

**Comment by deBasMan21** [comment]
Works perfectly! Thanks :)
